# this is a drone yaml file
build:
  image: ciscocloud/mantl
  commands:
    - export AWS_ACCESS_KEY_ID=$$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$$AWS_SECRET_ACCESS_KEY
    - testing/integration-test.sh
